pets:
  - name: 'Niffler'
    permission: 'pet.niffler'
    description: 'A cute little coin-eating Niffler.'
    idle: 13
    interact: 14
    rideable: false
    shoulder: false
    walk:
      - 10
      - 11
      - 12
  - name: 'Bowtruckle'
    permission: 'pet.bowtruckle'
    description: 'A little twig-legged Bowtruckle to be your companion.'
    idle: 32
    interact: 33
    rideable: false
    shoulder: true
    walk:
      - 29
      - 30
      - 31
  - name: 'Mooncalf'
    permission: 'pet.mooncalf'
    description: 'A dancing moonlight companion.'
    idle: 28
    rideable: false
    shoulder: false
    walk:
      - 25
      - 26
      - 27
  - name: 'Demiguise'
    permission: 'pet.demiguise'
    description: 'A future-seeing, translucent creature.'
    idle: 37
    interact: 38
    rideable: false
    shoulder: false
    walk:
      - 34
      - 35
      - 36
  - name: 'Thunderbird Hatchling'
    permission: 'pet.thunderbirdhatchling'
    description: 'A beautiful bird, crackling with electricity.'
    rideable: false
    shoulder: false
    idle: 40
    walk:
      - 41
      - 42
      - 43
  - name: 'House Elf'
    permission: 'pet.houseelf'
    description: 'A wide-eyed creature indebted to your servitude.'
    idle: 46
    rideable: false
    shoulder: false
    walk:
      - 47
      - 48
      - 49

messages:
  shoulder_equipped: '&8(&3&lPets&8) &7Your &3&l$pet &7now rests on your shoulder.'
  no_swap: '&4&lX &cThat pet cannot leave your shoulder! Click it in your inventory to remove it.'
  dequipped_pet: '&8(&3&lPets&8) &7Your &3&l$pet &7has been removed.'
  following_equipped: '&8(&3&lPets&8) &7Your &3&l$pet &7is now following you!'
  dont_own_pet: "&4&lX &cYou don't own this pet! Purchase it at &3http://rowlingsrealm.com/store"
  only_players: '&4&lX &cOnly players can do that!'
  no_permission: '&4&lX &cYou do not have permission to do that!'
  not_enabled: '&4&lX &cThis pet is coming soon!'