item: DIAMOND_AXE
pets:
  - name: 'Niffler'
    permission: 'pet.niffler'
    idle: 13
    interact: 14
    rideable: false
    shoulder: false
    walk:
      - 10
      - 11
      - 12
  - name: 'Bowtruckle'
    permission: 'pet.bowtruckle'
    idle: 32
    interact: 33
    rideable: false
    shoulder: true
    walk:
      - 29
      - 30
      - 31
  - name: 'Mooncalf'
    permission: 'pet.mooncalf'
    idle: 28
    rideable: false
    shoulder: false
    walk:
      - 25
      - 26
      - 27
  - name: 'Demiguise'
    permission: 'pet.demiguise'
    idle: 37
    interact: 38
    rideable: false
    shoulder: false
    walk:
      - 34
      - 35
      - 36
  - name: 'Thunderbird Hatchling'
    permission: 'pet.thunderbirdhatchling'
    rideable: false
    shoulder: false
    walk:
      - 40
      - 41
      - 42
      - 43
  - name: 'House Elf'
    permission: 'pet.houseelf'
    idle: 46
    rideable: false
    shoulder: false
    walk:
      - 47
      - 48
      - 49